# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Expo Plugin and example CI for PR

on:
  pull_request:

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --immutable
      - run: yarn prepare
      - uses: actions/cache/save@v3
        with:
          path: |
            build
            plugin/build
            !node_modules
          key: ${{ github.sha }}

  example-basic:
    needs: build-plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/basic
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache/restore@v3
        with:
          path: |
            build
            plugin/build
            !node_modules
          key: ${{ github.sha }}
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn prebuild

  example-expo-router:
    needs: build-plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/expo-router
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache/restore@v3
        with:
          path: |
            build
            plugin/build
            !node_modules
          key: ${{ github.sha }}
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn prebuild
